services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    secrets:
      - db_password
      - wp_user_password
      - wp_admin_password
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm || pgrep php-fpm8.2 || pgrep php-fpm7.4"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception
    restart: always

  adminer:
    build: ./requirements/adminer
    container_name: adminer
    networks:
      - inception
    restart: always

  redis:
    build: ./requirements/redis
    container_name: redis
    networks:
      - inception
    restart: always

  static:
    build: ./requirements/static
    container_name: static
    networks:
      - inception
    restart: always

  ftp:
    build: ./requirements/ftp
    container_name: ftp
    env_file:
      - .env
    secrets:
      - ftp_password
    volumes:
      - wp_data:/var/www/html
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - inception
    restart: always

  portainer:
    build: ./requirements/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mlavry/data/mariadb

  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mlavry/data/wordpress
  
  portainer_data:

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
