FROM debian:bookworm

RUN apt-get update && apt-get install -y \
	vsftpd \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

COPY tools/vsftpd.conf /etc/vsftpd.conf
COPY tools/setup.sh /setup.sh

RUN chmod +x /setup.sh

CMD ["/setup.sh"]
